# Generated by Django 4.1.7 on 2023-03-22 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='appl_submitted',
        ),
    ]
