# Generated by Django 4.1.7 on 2023-03-22 03:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0002_remove_job_appl_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='appl_submitted',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
